from tkinter import *

window = Tk()
window.geometry('330x300')
window.title('Calculator')

e=Label(window,bg="white",pady=15,padx=150 )
e.grid(row=0,column=0,columnspan=10,sticky=W+E,padx=10,pady=5)
b1=Button(window,text="1",height=2,width=2)
b2=Button(window,text="2",height=2,width=2)
b3=Button(window,text="3",height=2,width=2)
b4=Button(window,text="4",height=2,width=2)
b5=Button(window,text="5",height=2,width=2)
b6=Button(window,text="6",height=2,width=2)
b7=Button(window,text="7",height=2,width=2)
b8=Button(window,text="8",height=2,width=2)
b9=Button(window,text="9",height=2,width=2)
bdot=Button(window,text=".",height=2,width=2)
bzero=Button(window,text="0",height=2,width=2)
bequal=Button(window,text="=",height=2,width=2)
badd=Button(window,text="+",height=2,width=2)
bminus=Button(window,text="-",height=2,width=2)
bmul=Button(window,text="x",height=2,width=2)
bdiv=Button(window,text="/",height=2,width=2)
bclear=Button(window,text="clr",height=2,width=2)
b1.grid(row=1,column=0,padx=10,pady=5)
b2.grid(row=1,column=1,padx=10,pady=5)
b3.grid(row=1,column=2,padx=10,pady=5)
b4.grid(row=2,column=0,padx=10,pady=5)
b5.grid(row=2,column=1,padx=10,pady=5)
b6.grid(row=2,column=2,padx=10,pady=5)
b7.grid(row=3,column=0,padx=10,pady=5)
b8.grid(row=3,column=1,padx=10,pady=5)
b9.grid(row=3,column=2,padx=10,pady=5)
bdot.grid(row=4,column=0,padx=10,pady=5)
bzero.grid(row=4,column=1,padx=10,pady=5)
bequal.grid(row=4,column=2,padx=10,pady=5)
badd.grid(row=1,column=4,padx=10,pady=5)
bminus.grid(row=2,column=4,padx=10,pady=5)
bmul.grid(row=3,column=4,padx=10,pady=5)
bdiv.grid(row=4,column=4,padx=10,pady=5)
bclear.grid(row=1,column=5,padx=10,pady=5)

window.mainloop()